pub mod application;
pub mod candidate;
pub mod company;
pub mod discovery;
pub mod error;
pub mod governance;
pub mod identity;
pub mod opportunity;
pub mod saved;
pub mod taxonomy;

pub use application::{Application, ApplicationStatus, NewApplication};
pub use candidate::{Candidate, CandidateEducation, CandidateExperience, CandidateResume};
pub use company::{Company, CompanyMembership, CompanyRole, CompanyVerificationStatus, NewCompany};
pub use discovery::{CompanySummary, OpportunitySearchResult, SearchPageResult, SearchQuery, SortBy};
pub use error::DomainError;
pub use governance::{AdminRole, AuditLog, ModerationCase, Report, VerificationStatus};
pub use identity::{Email, NewUser, RawPassword, User, UserStatus};
pub use opportunity::{NewOpportunity, Opportunity, OpportunityStatus, OpportunityType, RemoteScope, Salary, WorkplaceType};
pub use saved::{CandidatePreferences, SavedCompany, SavedOpportunity, SavedSearch};
pub use taxonomy::{Category, ExperienceLevel, Industry, Occupation, Skill, SkillAlias};